minimumReleaseAge: 8640
minimumReleaseAgeExclude:
    - '@types/bun'
    - '@awsless/*'
    - '@terraforge/*'
    - typescript
    - rolldown
    - '@oxc-project/*'
    - '@rolldown/*'

packages:
    - 'packages/*'
