export { sqsClient } from './client'
export { sendMessage, sendMessageBatch } from './commands'
export { mockSQS } from './mock'
export { sqsStruct } from './struct'
export { SendMessageOptions, BatchItem, SendMessageBatchOptions } from './types'
