// The vitest globals, declared instead of imported so importing this
// module never adds a runtime vitest dependency.
declare const vi: (typeof import('vitest'))['vi']
declare const beforeEach: (typeof import('vitest'))['beforeEach']
declare const afterEach: (typeof import('vitest'))['afterEach']
declare const expect: (typeof import('vitest'))['expect']
import { getAlertName } from '../server/alert.js'
import { setConfigValue } from '../server/config.js'
import { getCronName } from '../server/cron.js'
import { getFunctionName } from '../server/function.js'
import { getInstanceQueueName } from '../server/instance.js'
import { getJobName } from '../server/job.js'
import { getPubSubPublisherName } from '../server/pubsub.js'
import { getQueueName } from '../server/queue.js'
import { getSearchProps } from '../server/search.js'
import { getTableName } from '../server/table.js'
import { getTaskName } from '../server/task.js'
import { getTopicName } from '../server/topic.js'
import { hookTestCleanup } from './cleanup.js'
import type { TestMockFunction } from './mock.js'

// Generated by the cli from the app config. The cli imports this type,
// so producer & consumer can't drift.
export type TestManifest = {
	app: string
	region: string
	configs: Record<string, string>
	tables: unknown[]
	tableKeys: { stack: string; id: string; keys: unknown }[]
	// Tables with a stream consumer: the real handler runs on every
	// write, settled before the write resolves.
	streams: { stack: string; id: string; file: string; hash: string; sort?: string }[]
	// The declared search indexes, created per test file on the shared
	// run-wide opensearch server.
	searches: { stack: string; id: string; mappings: unknown; settings?: unknown }[]
	functions: { stack: string; id: string; file: string }[]
	tasks: { stack: string; id: string; file: string }[]
	// Crons run their real handler on a manual Cron.x.y() trigger.
	crons?: { stack: string; id: string; file: string }[]
	// A queue without a consumer still mocks its send.
	queues: { stack: string; id: string; file?: string }[]
	topics: string[]
	pubsub: string[]
	caches: { stack: string; id: string }[]
	alerts: string[]
	jobs: { stack: string; id: string }[]
	instances: { stack: string; id: string }[]

	// The shared resource servers the cli boots once for the whole test
	// run - test files namespace into them instead of booting their own.
	servers?: {
		redis?: { host: string; port: number }
		search?: { endpoint: string }
	}
}

type ImportFile = (file: string) => Promise<any>

// Overrides registered outside a running test (module or describe scope)
// are the baseline every test starts from; overrides inside a test are temporary.
export const mockBaselines = new Map<TestMockFunction, (...args: unknown[]) => unknown>()
export const mockState = { inTest: false }

type Registry = Record<string, TestMockFunction>

// Every materialized resource spy, keyed by its physical name - the
// `mock` proxy resolves overrides & assertions through this registry.
export const testRegistry = {
	emails: {} as Registry,
	functions: {} as Registry,
	crons: {} as Registry,
	tasks: {} as Registry,
	// The scheduled invokes of a task, apart from its direct invokes.
	schedules: {} as Registry,
	queues: {} as Registry,
	topics: {} as Registry,
	pubsub: {} as Registry,
	alerts: {} as Registry,
	jobs: {} as Registry,
	instances: {} as Registry,
}

// Materialize the whole app for a test file; the `mock` api overrides any part of it.
export const setupTestEnv = async (manifest: TestManifest, options: { importFile: ImportFile }) => {
	// Lazy, so importing awsless stays free of test machinery outside test runs.
	const [dynamodb, lambda, s3, scheduler, sns, sqs, cloudwatch, ecs, ses] = await Promise.all([
		import('@awsless/dynamodb'),
		import('@awsless/lambda'),
		import('@awsless/s3'),
		import('@awsless/scheduler'),
		import('@awsless/sns'),
		import('@awsless/sqs'),
		import('@awsless/cloudwatch'),
		import('@awsless/ecs'),
		import('@awsless/ses'),
	])

	// Metrics are recorded into the void.
	cloudwatch.mockCloudWatch()

	// Registered during collection, since hooks can't register inside a
	// running test - resources like cache clients clean up through it.
	hookTestCleanup()

	compareBigFloatsByValue()
	applyTestConfigValues(manifest)
	materializeTables(manifest, options.importFile, dynamodb)
	await createSearchIndexes(manifest)

	// Stores ride an in-memory s3.
	s3.mockS3()

	await redirectCacheClients(manifest)

	const spies = registerResourceSpies(manifest, options.importFile)

	lambda.mockLambda(spies.lambdas)
	scheduler.mockScheduler(spies.schedules)
	sqs.mockSQS(spies.queues)
	sns.mockSNS(spies.topics)
	ecs.mockEcs(spies.jobs)

	recordEmails(ses.mockSES)
	resetSpiesBetweenTests()
}

// Lazily imports the real handler, so cross stack calls test the real contract.
const realHandler = (importFile: ImportFile, file: string) => {
	let cached: Promise<(payload: unknown) => unknown> | undefined

	return vi.fn((payload: unknown) => {
		cached ??= importFile(file).then(
			module => {
				const handle = module.default

				if (typeof handle !== 'function') {
					throw new Error(`The handler file has no default export: ${file}`)
				}

				return handle
			},
			// A failed import must not stick: the next call retries
			// instead of replaying the same rejection for every test.
			error => {
				cached = undefined
				throw error
			}
		)

		return cached.then(handle => handle(payload))
	})
}

// Arithmetic keeps a denormalized big float representation while transport
// round trips normalize it, so equality must compare by numeric value.
const compareBigFloatsByValue = () => {
	const isBigFloat = (value: unknown): value is { toString: () => string } =>
		typeof value === 'object' &&
		value !== null &&
		typeof (value as { coefficient?: unknown }).coefficient === 'bigint' &&
		typeof (value as { exponent?: unknown }).exponent === 'number'

	expect.addEqualityTesters([
		function (a, b) {
			if (isBigFloat(a) && isBigFloat(b)) {
				return a.toString() === b.toString()
			}

			return undefined
		},
	])
}

// The test config values are set before any test file import resolves,
// so import time Config reads just work.
const applyTestConfigValues = (manifest: TestManifest) => {
	for (const [name, value] of Object.entries(manifest.configs)) {
		setConfigValue(name, value)
	}
}

const materializeTables = (
	manifest: TestManifest,
	importFile: ImportFile,
	dynamodb: Awaited<typeof import('@awsless/dynamodb')>
) => {
	if (manifest.tables.length === 0) {
		return
	}

	// The app prefix may be unique per test file, so the physical
	// table names follow it.
	const app = process.env.APP!
	const tables = (manifest.tables as { TableName: string }[]).map(table => ({
		...table,
		TableName: table.TableName.replace(`${manifest.app}--`, `${app}--`),
	}))

	// Streams settle before the write resolves, so a test observes the consumer's effects directly.
	const streams = (manifest.streams ?? []).map(entry => {
		return dynamodb.streamTable(
			dynamodb.define(getTableName(entry.id, entry.stack), {
				hash: entry.hash,
				sort: entry.sort,
				schema: dynamodb.object({}, dynamodb.any()),
			}),
			async payload => {
				const consumer = await importFile(entry.file)
				await consumer.default(payload)
			}
		)
	})

	dynamodb.mockDynamoDB({ tables: tables as any, stream: streams })
}

// The declared search indexes exist on the shared run-wide search
// server before any test runs, namespaced by the app prefix.
const createSearchIndexes = async (manifest: TestManifest) => {
	const endpoint = manifest.servers?.search?.endpoint

	if (!endpoint) {
		return
	}

	for (const entry of manifest.searches ?? []) {
		const { name } = getSearchProps(entry.id, entry.stack)

		// The declared mappings let the search define verify the code
		// schema against the stack file.
		process.env[`SEARCH_MAPPINGS_${name}`] = JSON.stringify(entry.mappings)

		const result = await fetch(`${endpoint}/${name}`, {
			method: 'PUT',
			headers: { 'content-type': 'application/json' },
			body: JSON.stringify({ mappings: entry.mappings, settings: entry.settings }),
		})

		if (!result.ok) {
			throw new Error(`Failed to create the search index "${name}": ${await result.text()}`)
		}
	}
}

// Cache clients redirect to a real local redis, exactly like the local
// dev environment runs real redis.
const redirectCacheClients = async (manifest: TestManifest) => {
	if ((manifest.caches ?? []).length === 0) {
		return
	}

	const shared = manifest.servers?.redis

	if (!shared) {
		const { mockRedis } = await import('@awsless/redis')

		mockRedis()

		return
	}

	// One database per vitest worker, flushed per file. Concurrent vitest
	// instances number workers from 1, so the runner's offset keeps them disjoint.
	const { createIoRedisClient, overrideOptions } = await import('@awsless/redis')
	const offset = parseInt(process.env.AWSLESS_TEST_REDIS_DB_OFFSET ?? '0', 10) || 0
	const db = (offset + (parseInt(process.env.VITEST_POOL_ID ?? '1', 10) || 1)) % 256

	overrideOptions({
		host: shared.host,
		port: shared.port,
		db,
		cluster: false,
		tls: undefined,
		// A full-suite run can transiently overload the local server's accept
		// queue; the client default gives up after ~300ms, which fails the run.
		maxRetriesPerRequest: 20,
		connectTimeout: 10_000,
		retryStrategy: times => (times > 20 ? null : Math.min(times * 250, 2000)),
	})

	const flush = async () => {
		const client = createIoRedisClient({ host: shared.host, port: shared.port, db })

		try {
			await client.send('FLUSHDB', [])
		} finally {
			await client.destroy()
		}
	}

	// A hiccup here fails unrelated stacks, so retry once; the raw error
	// only says ECONNREFUSED without saying what refused.
	try {
		await flush()
	} catch (error) {
		await new Promise(resolve => setTimeout(resolve, 1000))

		try {
			await flush()
		} catch (retryError) {
			throw new Error(
				`The shared test redis server at ${shared.host}:${shared.port} is unreachable: ${String(error)}`,
				{ cause: retryError }
			)
		}
	}
}

// One spy per resource under its physical name: consumers run their real
// handler, publish-only resources record as no-ops.
const registerResourceSpies = (manifest: TestManifest, importFile: ImportFile) => {
	const spies = {
		lambdas: {} as Registry,
		schedules: {} as Registry,
		queues: {} as Registry,
		topics: {} as Registry,
		jobs: {} as Registry,
	}

	for (const entry of manifest.functions) {
		const name = getFunctionName(entry.id, entry.stack)
		const spy = realHandler(importFile, entry.file)

		testRegistry.functions[name] = spy
		spies.lambdas[name] = spy
	}

	for (const entry of manifest.crons ?? []) {
		const name = getCronName(entry.id, entry.stack)
		const spy = realHandler(importFile, entry.file)

		testRegistry.crons[name] = spy
		spies.lambdas[name] = spy
	}

	// A schedule records on its own spy & then runs the task, so a test
	// can tell the two apart while the scheduled work still happens.
	for (const entry of manifest.tasks) {
		const name = getTaskName(entry.id, entry.stack)
		const spy = realHandler(importFile, entry.file)
		const scheduled = vi.fn((payload: unknown) => spy(payload))

		testRegistry.tasks[name] = spy
		testRegistry.schedules[name] = scheduled
		spies.lambdas[name] = spy
		spies.schedules[name] = scheduled
	}

	for (const id of manifest.pubsub) {
		const name = getPubSubPublisherName(id)
		const spy = vi.fn(() => {})

		testRegistry.pubsub[name] = spy
		spies.lambdas[name] = spy
	}

	// A producer-only queue (no consumer) records the sends as a no-op
	// spy, so a valid send never throws.
	for (const entry of manifest.queues) {
		const name = getQueueName(entry.id, entry.stack)
		const spy = entry.file ? realHandler(importFile, entry.file) : vi.fn(() => {})

		testRegistry.queues[name] = spy
		spies.queues[name] = spy
	}

	for (const id of manifest.topics) {
		const name = getTopicName(id)
		const spy = vi.fn(() => {})

		testRegistry.topics[name] = spy
		spies.topics[name] = spy
	}

	// Alerts ride the same sns mock as the topics.
	for (const id of manifest.alerts ?? []) {
		const name = getAlertName(id)
		const spy = vi.fn(() => {})

		testRegistry.alerts[name] = spy
		spies.topics[name] = spy
	}

	// Instance code is a long running poller, not a handler, so sends record as no-ops.
	for (const entry of manifest.instances ?? []) {
		const name = getInstanceQueueName(entry.id, entry.stack)
		const spy = vi.fn(() => {})

		testRegistry.instances[name] = spy
		spies.queues[name] = spy
	}

	if ((manifest.jobs ?? []).length > 0) {
		// Job.x() reads the network env vars before reaching the mocked ecs client.
		process.env.JOB_SUBNETS ??= JSON.stringify(['subnet-local'])
		process.env.JOB_SECURITY_GROUP ??= 'sg-local'
	}

	for (const entry of manifest.jobs ?? []) {
		const name = getJobName(entry.id, entry.stack)
		const spy = vi.fn(() => {})

		testRegistry.jobs[name] = spy
		spies.jobs[name] = spy
	}

	return spies
}

// Every Email.send records on the email spy instead of reaching ses,
// with the payload flattened for readable assertions.
const recordEmails = (mockSES: Awaited<typeof import('@awsless/ses')>['mockSES']) => {
	testRegistry.emails.send = vi.fn(() => {})

	mockSES(input => {
		const email = input as {
			FromEmailAddress?: string
			Destination?: { ToAddresses?: string[] }
			Content?: { Simple?: { Subject?: { Data?: string }; Body?: { Html?: { Data?: string } } } }
		}

		testRegistry.emails.send!({
			from: email.FromEmailAddress,
			to: email.Destination?.ToAddresses,
			subject: email.Content?.Simple?.Subject?.Data,
			html: email.Content?.Simple?.Body?.Html?.Data,
		})
	})
}

// A fake set up inside one test must not leak into the next, while
// module scope overrides persist as the baseline.
const resetSpiesBetweenTests = () => {
	beforeEach(() => {
		mockState.inTest = true

		for (const registry of Object.values(testRegistry)) {
			for (const spy of Object.values(registry)) {
				spy.mockReset()

				const baseline = mockBaselines.get(spy)

				if (baseline) {
					spy.mockImplementation(baseline)
				}
			}
		}
	})

	afterEach(() => {
		mockState.inTest = false
	})
}
